/*
This file is part of the Twainsave-opensource version
Copyright (c) 2002-2025 Dynarithmic Software.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

FOR ANY PART OF THE COVERED WORK IN WHICH THE COPYRIGHT IS OWNED BY
DYNARITHMIC SOFTWARE. DYNARITHMIC SOFTWARE DISCLAIMS THE WARRANTY OF NON INFRINGEMENT
OF THIRD PARTY RIGHTS.
*/
#ifndef TWAINSAVE_VERINFO_H
#define TWAINSAVE_VERINFO_H

#define TWAINSAVE_STRINGER_2_(x) #x
#define TWAINSAVE_STRINGER_(x) TWAINSAVE_STRINGER_2_(x)

#define TWAINSAVE_MAJOR_VERSION 1
#define TWAINSAVE_MINOR_VERSION 3
#define TWAINSAVE_PATCH_VERSION 1

#define TWAINSAVE_BUILDVERSION_TOP 0
#define TWAINSAVE_BUILDVERSION_MIDDLE 0
#define TWAINSAVE_BUILDVERSION_BOTTOM 1

#define TWAINSAVE_BASE_VERSION TWAINSAVE_STRINGER_(TWAINSAVE_MAJOR_VERSION) "." TWAINSAVE_STRINGER_(TWAINSAVE_MINOR_VERSION) "." TWAINSAVE_STRINGER_(TWAINSAVE_PATCH_VERSION)
#define TWAINSAVE_BUILD_VERSION  TWAINSAVE_STRINGER_(TWAINSAVE_BUILDVERSION_TOP) TWAINSAVE_STRINGER_(TWAINSAVE_BUILDVERSION_MIDDLE) TWAINSAVE_STRINGER_(TWAINSAVE_BUILDVERSION_BOTTOM)
#define TWAINSAVE_FULL_VERSION TWAINSAVE_BASE_VERSION " Build " TWAINSAVE_BUILD_VERSION

#ifdef _MSC_VER
    #pragma message ( "Building TwainSave, Version " TWAINSAVE_FULL_VERSION)
#endif

#define TWAINSAVE_VERINFO_COMMENTS          "TwainSave (Open Source)\0"
#define TWAINSAVE_VERINFO_COMPANYNAME       "Dynarithmic Software\0"
#define TWAINSAVE_VERINFO_LEGALCOPYRIGHT	"Copyright   2020-2026\0"
#define TWAINSAVE_VERINFO_PRODUCTNAME		"TwainSave (Open Source)\0"
#define TWAINSAVE_VERINFO_ORIGINALFILENAME  "twainsave-opensource.exe\0"
#define TWAINSAVE_VERINFO_INTERNALNAME      "twainsave-opensource.exe\0"
#define TWAINSAVE_VERINFO_LEGALTRADEMARKS   "Dynarithmic Software\0"
#define TWAINSAVE_VERINFO_FILEDESCRIPTION   "twainsave-opensource\0"
#define TWAINSAVE_VERINFO_SPECIALBUILD      "Open Source Version\0"
#define TWAINSAVE_VERINFO_PRIVATEBUILD      "Open Source Version\0"

#define TWAINSAVE_NUMERIC_FILE_VERSION         TWAINSAVE_MAJOR_VERSION,TWAINSAVE_MINOR_VERSION,TWAINSAVE_PATCH_VERSION
#define TWAINSAVE_VERINFO_FILEVERSION          TWAINSAVE_FULL_VERSION
#define TWAINSAVE_NUMERIC_PRODUCT_VERSION      TWAINSAVE_MAJOR_VERSION,TWAINSAVE_MINOR_VERSION,TWAINSAVE_PATCH_VERSION
#define TWAINSAVE_VERINFO_PRODUCTVERSION       TWAINSAVE_FULL_VERSION
#endif
